# Generated by Django 6.1.1 on 2026-10-03 17:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=12, unique=True)),
                ('descripcion', models.TextField(verbose_name='Descripción del avance')),
                ('fecha', models.DateField(verbose_name='Fecha de realización')),
                ('foto_antes', models.ImageField(upload_to='actividades/antes/')),
                ('foto_despues', models.ImageField(upload_to='actividades/despues/')),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='adminApp.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'actividades',
                'ordering': ['-creado'],
            },
        ),
    ]
