# Generated by Django 6.1 on 2026-10-05 20:19

import usuarioApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarioApp', '0003_actividad_usuario_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='foto_antes',
            field=models.ImageField(upload_to=usuarioApp.models.ruta_foto_antes),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='foto_despues',
            field=models.ImageField(upload_to=usuarioApp.models.ruta_foto_despues),
        ),
    ]
