# Generated by Django 6.1.1 on 2026-10-03 17:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, help_text='Qué se debe realizar.')),
                ('area', models.CharField(help_text='Ej: Obras, Áreas Verdes, Alumbrado.', max_length=80)),
                ('ubicacion', models.CharField(blank=True, max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tareas',
                'ordering': ['-creado'],
            },
        ),
    ]
