# Generated by Django 6.1 on 2026-10-05 19:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_asignar_tareas_existentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('username', models.CharField(blank=True, help_text='Usuario escrito o involucrado (se conserva aunque la cuenta no exista).', max_length=150)),
                ('accion', models.CharField(choices=[('LOGIN_OK', 'Inicio de sesión'), ('LOGIN_FALLIDO', 'Inicio de sesión fallido'), ('LOGIN_BLOQUEADO', 'Inicio bloqueado por intentos'), ('LOGOUT', 'Cierre de sesión'), ('ACCESO_DENEGADO', 'Acceso denegado por rol'), ('MEDIA_DENEGADA', 'Foto de otro usuario denegada'), ('TAREA_CREADA', 'Tarea creada'), ('TAREA_EDITADA', 'Tarea editada'), ('TAREA_ELIMINADA', 'Tarea eliminada'), ('REPORTE_ENVIADO', 'Reporte enviado'), ('REPORTE_EVALUADO', 'Reporte evaluado')], db_index=True, max_length=20)),
                ('objeto', models.CharField(blank=True, db_index=True, help_text='Elemento afectado, ej: ACT-7K3M o tarea:5.', max_length=40)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'db_table': 'auditoria',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
